-- SQLite
SELECT COUNT(*) FROM DEPARTMENTS;
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(*) FROM JOBS;
SELECT COUNT(*) FROM JOB_HISTORY;
SELECT COUNT(*) FROM LOCATIONS;

SELECT * FROM EMPLOYEES LIMIT 5;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 10;

SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LIMIT 10;

SELECT * 
FROM JOBS
WHERE JOB_TITLE =Jr. Designer;

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT EMPLOYEE_ID, SALARY, 
       (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) 
FROM (
    SELECT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
    LIMIT 5
) AS SALARY_TABLE;

SELECT COUNT(*) 
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

PRAGMA table_info(<tabelnaam>);

SELECT * FROM EMPLOYEES LIMIT 1;

PRAGMA table_info(DEPARTMENTS);

PRAGMA table_info(EMPLOYEES);
PRAGMA table_info(JOBS);
PRAGMA table_info(JOB_HISTORY);
PRAGMA table_info(LOCATIONS);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS);

SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_ID
FROM JOBS
WHERE JOB_ID IN (select JOB_ID from EMPLOYEES where SALARY > 70000 );

PRAGMA table_info(JOBS);

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.SALARY, e.JOB_ID, j.JOB_TITLE
FROM EMPLOYEES e
INNER JOIN JOBS j ON e.JOB_ID = j.JOB_IDENT
WHERE e.SALARY > 70000;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY > 500;

SELECT *
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;

SELECT *
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT JOB_ID, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 5 AND 80000;

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN (30001, 30003, 30002);


SELECT JOB_ID, COUNT(*) AS aantal_medewerkers
FROM EMPLOYEES
WHERE JOB_ID IN (30001, 30003, 30002)
GROUP BY JOB_ID;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 600;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY <= 40000;

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN (30001, 30002, 30003);

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID NOT IN (30001, 30002, 30003);

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 450 AND SALARY < 60000;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%s';

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%';

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 650;